name: .NET CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore API only
      run: |
        dotnet restore OnlineCourses.API/OnlineCourses.API.csproj
        dotnet restore OnlineCourses.Data/OnlineCourses.Data.csproj
        dotnet restore OnlineCourses.Models/OnlineCourses.Models.csproj
        dotnet restore OnlineCourses.Tests/OnlineCourses.Tests.csproj
    
    - name: Build API only
      run: |
        dotnet build OnlineCourses.API/OnlineCourses.API.csproj -c Release --no-restore
        dotnet build OnlineCourses.Data/OnlineCourses.Data.csproj -c Release --no-restore
        dotnet build OnlineCourses.Models/OnlineCourses.Models.csproj -c Release --no-restore
        dotnet build OnlineCourses.Tests/OnlineCourses.Tests.csproj -c Release --no-restore
    
    - name: Test
      run: dotnet test OnlineCourses.Tests/OnlineCourses.Tests.csproj -c Release --no-build --verbosity normal